Fix use of Macro::getNumeric as test
Return value should not depend on whether 'ret' is null;
otherwise we get this failure:

  Error: java/genBinaryBlob.cpp:770 addBlobConst - Adding
  more constants than enumerated

Issue: eclipse/openj9#378
Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>