CMake: Add validation to OMR_THR_YIELD_ALG option
Check that platform is supported if OMR_THR_YIELD_ALG is enabled.
Previously, if it were enabled on an unsupported platform, the result
would be a link error due to undefined reference to `THREAD_YIELD_NEW`

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>