Fix compile error with Concurrent Scavenger enabled on macOS
Removed unused private field `_bytesToScan` from
`ConcurrentScavengeTask` to resolve:

```
/ConcurrentScavengeTask.hpp:38:18: error: private field '_bytesToScan'
is not used [-Werror,-Wunused-private-field]
uintptr_t const _bytesToScan;   /**< The number of bytes that this must
scan before it will stop trying to do more work */
```

Signed-off-by: Salman Rana <salman.rana@ibm.com>