Fix Linux compiler warnings when DUMP_DBG is defined
If DUMP_DBG is defined on Linux, then five warnings are emitted:

./linux/omrosdump_helpers.c:783:6: error: variable 'bytesread' set but not used [-Werror,-Wunused-but-set-variable]
        int bytesread = 0;
            ^
./linux/omrosdump_helpers.c:782:6: error: variable 'offset' set but not used [-Werror,-Wunused-but-set-variable]
        int offset = 0;
            ^
./linux/omrosdump_helpers.c: In function 'printMemoryMap':
./linux/omrosdump_helpers.c:823:14: error: variable 'device' set but not used [-Werror=unused-but-set-variable]
  823 |         char device[6];

./linux/omrosdump_helpers.c:827:6: error: variable 'inode' set but not used [-Werror,-Wunused-but-set-variable]
        int inode;
            ^
./linux/omrosdump_helpers.c:825:6: error: variable 'offset' set but not used [-Werror,-Wunused-but-set-variable]
        int offset;

The use of J9_IGNORE_RETURNVAL prevents four of these warnings, while device can be skipped over as per the code in getSharedAndPrivateDataSegments.

Signed-off-by: David McCann <mccannd@uk.ibm.com>