Prevent sign-compare warning from createTest.cpp
In newer compilers that include -Wsign-compare as part of -Wall (for example gcc 11) a compiler warning is emitted from fvtest/threadtest/createTest.cpp:

g++  -I. -I../../fvtest/util -I../../third_party/gtest-1.8.0 -I../../third_party/gtest-1.8.0/include -I../../fvtest/omrGtestGlue -I../../thread -I../../include_core -I../../nls -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DJ9HAMMER -c -MMD -MP -fno-strict-aliasing -std=c++0x -fno-exceptions -fno-rtti -fno-threadsafe-statics -fPIC -ggdb -m64 -Wreturn-type -Werror -Wall -Wno-non-virtual-dtor -O0 -fexceptions  -o createTest.o createTest.cpp
createTest.cpp: In function 'size_t getOsStacksize(size_t)':
createTest.cpp:497:42: error: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'long int' [-Werror=sign-compare]
  497 |                 if (pageSafeMinimumStack < PTHREAD_STACK_MIN) {
      |                                          ^

Change pageSafeMinimumStack to be a uintptr_t (and also in omrthreadattr.c) and perform a cast in the comparison with PTHREAD_STACK_MIN. Change getOsStackSize to take and return uintptr_t since the expected stacksize is a uintptr_t already.

Signed-off-by: David McCann mccannd@uk.ibm.com