Update Port.cpp and omrsharedhelper.c to fix gcc11 compilation
The code fails to compile on zlinux with gcc 11.2 without fixes.
```
Port.cpp: In static member function 'static RCType
Port::omrfile_stat(const char*, unsigned int, J9FileStat*)':
Port.cpp:691:14: error: narrowing conversion of '4283649346' from
'unsigned int' to 'int'
[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wnarrowing]
  691 |         case 0xFF534D42: /* CIFS_MAGIC_NUMBER */
      |              ^~~~~~~~~~
```

This one fails to compile on 32-bit.
```
In file included from /usr/include/string.h:637,
                 from ./unix/omrsharedhelper.c:34:
./unix/omrsharedhelper.c: In function 'omr_unlinkControlFile':
./unix/omrsharedhelper.c:419:9: error: '__builtin_strncpy' specified
bound depends on the length of the source argument
[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstringop-truncation]
  419 |         strncpy(originalErrMsg, currentErrMsg, msgLen);
      |         ^~~~~~~
./unix/omrsharedhelper.c:413:26: note: length computed here
  413 |         int32_t msgLen = strlen(currentErrMsg);
      |                          ^~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>