Change VLAs to on-heap allocation in OptTestDriver
The implementation of the `OptTestDriver` class contains a few VLAs and
can't be compiled by MSVC:

..\fvtest\compilertest\tests\OptTestDriver.cpp(60): error C2131:
expression did not evaluate to a constant
..\fvtest\compilertest\tests\OptTestDriver.cpp(60): note: failure was
caused by a read of a variable outside its lifetime
..\fvtest\compilertest\tests\OptTestDriver.cpp(60): note: see usage of
'this'
..\fvtest\compilertest\tests\OptTestDriver.cpp(87): error C2131:
expression did not evaluate to a constant
..\fvtest\compilertest\tests\OptTestDriver.cpp(87): note: failure was
caused by a read of a variable outside its lifetime

The on-stack allocations for VLAs were replaced with allocation on the
heap:

OptimizationStrategy *strategy = new OptimizationStrategy[_optimizations.size() + 1];
...

Signed-off-by: Pavel Samolysov <samolisov@gmail.com>