Check __cplusplus is defined before checking its value
If __cplusplus isn't defined when omrcomp.h is included, it can cause a compiler warning to be emitted (for example, on gcc 11 on the latest version of Fedora):

include_core/omrcomp.h:612:6: error: "__cplusplus" is not defined, evaluates to 0 [-Werror=undef]
  612 | #if (__cplusplus >= 201103L)

Signed-off-by: David McCann <mccannd@uk.ibm.com>