Workaround for unsupported GCC features on OSX
When using GCC 4.2.1 on OSX 10.10 Yosemite, the following errors are
seen:

In file included from /usr/include/os/object.h:27,
                 from /usr/include/dispatch/dispatch.h:48,
                 from .å./omr/include_core/./unix/thrdsup.h:74,
                 from ../omr/include_core/thrdsup.h:35,
                 from ../omr/include_core/thrtypes.h:32,
                 ...
/usr/include/os/base.h:113:20: error: missing binary operator before
token "("
/usr/include/os/base.h:119:54: error: missing binary operator before
token "("
In file included from /usr/include/dispatch/dispatch.h:51,
                 from ../omr/include_core/./unix/thrdsup.h:74,
                 from ../omr/include_core/thrdsup.h:35,
                 from ../omr/include_core/thrtypes.h:32,
                 ...
/usr/include/dispatch/object.h:325:20: error: missing binary operator
before token "("
/usr/include/dispatch/object.h:363:20: error: missing binary operator
before token "("
/usr/include/dispatch/object.h:391:20: error: missing binary operator
before token "("
/usr/include/dispatch/object.h:423:20: error: missing binary operator
before token "("

The above error happens because __has_extension and __has_feature macros
are undefined when using GCC 4.2.1 on OSX 10.10 Yosemite. The above
error also happens with other version of GCC.

Clang supports the missing macros so the above errors are not seen with
Clang.

For supporting OpenJ9 JDK8 on OSX, OMR needs to be built with GCC 4.2.1
on OSX 10.10 Yosemite.

Adding stubs for the missing macros before including dispatch.h resolves
the above errors.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>