Remove unused totalRegionsSize from omrvmemTest.cpp
Recent compilers, such as clang 13, that include -Wunused-but-set-variable in -Wall emit warnings about the use of totalRegionsSize in fvtest/porttest/omrvmemTest.cpp:

/var/build/tools/clang/13.0.0/bin/clang++  -I. -I../../port/common -I../util -I../../third_party/gtest-1.8.0 -I../../third_party/gtest-1.8.0/include -I../../fvtest/omrGtestGlue -I../../include_core -I../../nls -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DJ9HAMMER -c -MMD -MP -fno-strict-aliasing -std=c++0x -fno-exceptions -fno-rtti -fno-threadsafe-statics -fPIC -ggdb -m64 -Wreturn-type -Werror -Wall -Wno-non-virtual-dtor -O0 -fexceptions  -o omrvmemTest.o omrvmemTest.cpp
omrvmemTest.cpp:712:12: error: variable 'totalRegionsSize' set but not used [-Werror,-Wunused-but-set-variable]
        uintptr_t totalRegionsSize = 0;
                  ^
omrvmemTest.cpp:920:12: error: variable 'totalRegionsSize' set but not used [-Werror,-Wunused-but-set-variable]
        uintptr_t totalRegionsSize = 0;

totalRegionsSize isn't actually used so removing it gets rid of the warning.

Signed-off-by: David McCann mccannd@uk.ibm.com